"""initial_schema

Revision ID: 48d8d9246ea5
Revises: 
Create Date: 2026-06-10 12:05:48.607248

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401 — required for sqlmodel.sql.sqltypes references below
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d8d9246ea5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_track_remote_id'), ['remote_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_remote_id'))
        batch_op.alter_column('thumbnail',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
